spring:
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/Users/c.cozma/Desktop/projects/cosmin/instagram/src/main/resources/data/istagram;AUTO_SERVER=true;

  jpa:
    open-in-view: off